# Generated by Django 5.0.6 on 2024-05-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField(null=True)),
                ('patente_camion', models.CharField(max_length=6, null=True)),
                ('intento', models.IntegerField(default=0)),
                ('entregado', models.BooleanField(null=True)),
                ('id_compra', models.IntegerField(null=True)),
                ('direccion_compra', models.CharField(max_length=80, null=True)),
                ('valor_compra', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Despacho',
            },
        ),
        migrations.CreateModel(
            name='Resumen_Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField()),
                ('id_despacho', models.IntegerField()),
            ],
            options={
                'db_table': 'Resumen_Despacho',
            },
        ),
    ]
